Localization: zh-tw

Private:
  KeyChar: '#'
  canOthersFeed: false
  canOthersRide: false
  canKillbyEntity: true
  Entities:
    - HORSE

Public:
  KeyChar: '%'
  canOthersFeed: false
  canOthersRide: true
  canKillbyEntity: false
  Entities:
    - SHEEP
    - MUSHROOM_COW